### ISSUE TITLE
[Regression][Factory Tests] Sound sample is inaudible during the sound test

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#24] opened 2021-05-11 22:15 UTC
Sound cannot be heard in Factory Tests (Fn+START when booting the console).
I first thought it was because there were still some occurrences of "**start_audio_amp 0**" and "**start_audio_amp 1**"  in "/usr/local/sbin/volume_set" and "/usr/local/sbin/volume_set_alsa". But replacing them with "**audio_amp on**" and "**audio_amp off**" did not solve the issue (but I wanted to make sure you knew that some left).
This bug does not occur with OS 2.2.0 but only with a custom one built from [ffa35c0](https://github.com/FunKey-Project/FunKey-OS/commit/ffa35c0983b715576d9e3524d6cf291e9c58ae15) ("develop" branch).

1. Build an OS from [ffa35c0](https://github.com/FunKey-Project/FunKey-OS/commit/ffa35c0983b715576d9e3524d6cf291e9c58ae15) commit ("develop" branch)
2. Boot the console while pressing Fn+START
3. Launch the Factory Tests
4. Notice that you cannot hear any sound during the sound test (even at high volume)

**Expected behavior**
Sound should be audible during the Factory sound test.

**Comment by Michel-FK** [comment] 2021-05-13 20:07
Fixed in commit 547c1fe, the root cause was the same as issue #22 which only solved the problem for instant replay. I reverted the corresponding commit as this fix works for both cases.

**Closed by Michel-FK** 2021-05-13 20:07 UTC
Labels: bug

**Comment by DrUm78** [comment] 2021-05-13 23:24
Fixed and verified, thanks!
